#!/usr/bin/env python3
# -*- Python -*-

import os.path
import sys
import pickle
import re
from argparse import ArgumentParser

################################################################
# Common modules, functions

def log(x):
    if options.verbose:
        print(x, file=sys.stderr)

def warn_or_error(x, col):
    prefix = ""
    suffix = ""
    if os.isatty(sys.stderr.fileno()):
        prefix = "\x1b[" + str(col) + ";1m"
        suffix = "\x1b[0m"
    print(prefix + x + suffix, file=sys.stderr)

def warn(x):
    warn_or_error("Warning: " + x, 33)

def error(x):
    warn_or_error("Error: " + x, 31)
    sys.exit(1)

def safe_close(fh):
    # asynchronous NFS may miss file creation
    # esp. combined with delayed allocation (ext4, XFS)
    # The open-to-close consistency is preserved only when 
    fh.flush()
    os.fsync(fh.fileno())
    fh.close()

# End of common components
################################################################

parser = ArgumentParser()

# topology
parser.add_argument("-p", "--pdb", dest = "pdb",
                  help="Solution PDB (.pdb) file name to give molecular structure")

parser.add_argument("-v", "--verbose", dest = "verbose", action="store_true",
                  help = "Be more verbose",
                  default = False)

options = parser.parse_args()

if options.pdb == None:
    error("Error: PDB file is not specified (try --help)")

picked = 0
try:
    ifh = open("soln/.extraparam", "rt")
    carryover = pickle.load(ifh)
    ifh.close()
    if "sltspec" in carryover:
        picked = carryover["sltspec"] - 1
except OSError:
    pass

permindex = []
if os.path.exists("soln/PermIndex"):
    fh = open("soln/PermIndex", "r")
    for l in fh:
        ls = l.split()
        permindex.append(int(ls[0]) - 1)

# read topology from MDinfo

fh = open("soln/MDinfo", "rt")
mols = int(next(fh).split()[1])
ms = next(fh).split()
ms = [int(i) for i in ms]
ns = next(fh).split()
ns = [int(i) for i in ns]

assert mols == len(ms), "number of molecules does not match to MDinfo's 1st line"
assert mols == len(ns), "number of atoms does not match to MDinfo's 1st line"

if ms[picked] != 1:
    error("This script does not support multiple solute atoms case")

begins = []
t = 0
for i in range(mols):
    begins.append(t)
    t += ms[i] * ns[i]
# sentinel
begins.append(t)
totalatoms = t
fh.close()

molprms = []
molprmnum = 1
for i in range(mols):
    if i == picked:
        fn = "soln/SltInfo"
    else:
        fn = "soln/MolPrm%d" % molprmnum
        molprmnum += 1
    fh = open(fn, "rt")
    lines = fh.readlines()
    lines = [x.rstrip() for x in lines]
    fh.close()
    for j in range(ms[i]):
        molprms.extend(lines)
assert totalatoms == len(molprms), "Number of total lines in MolPrmX does not conform"

# read residues from PDB
fh = open(options.pdb, "rt")

atoms = []
for l in fh:
    if len(l) < 6 or (l[0:6] != "ATOM  " and l[0:6] != "HETATM"):
        continue
    resname = l[17:20].strip()
    resindex = int(l[22:26].strip())
    atoms.append((False, resname, resindex))
fh.close()

assert len(atoms) == totalatoms, "PDB has %d atoms but MDinfo indicates %d atoms" % (len(atoms), totalatoms)

if len(permindex) == 0: # there are no PermIndex file
    permindex = list(range(totalatoms))

# deep copy
permindex_refs = [i for i in permindex]

for i in range(begins[picked], begins[picked] + ns[picked]):
    permindex_refs[i] = None
    atoms[i] = (True, atoms[i][1], atoms[i][2])

for i in range(begins[picked] + ns[picked], totalatoms):
    permindex_refs[i] = permindex_refs[i] - ns[picked]

def str_of_list(ls):
    def add_result(a, b, ret):
        ret += ","
        if a == b:
            ret += str(a)
        else:
            ret += "%d-%d" % (a, b)
        return ret
    ret = ""
    prev = None
    prevstart = -1
    pos = 0
    while True:
        if prev != ls[pos] - 1:
            if prev != None:
                ret = add_result(prevstart, prev, ret)
            prevstart = ls[pos]
        prev = ls[pos]
        pos += 1
        if pos == len(ls):
            ret = add_result(prevstart, prev, ret)
            break
    return ret[1:]

def name_of(molpos):
    # single residue name -> residue name
    # multiple residue name -> residue number range
    resix = set()
    resnames = set()
    is_solute = False
    for i in range(begins[molpos], begins[molpos+1]):
        (is_solute_atom, rn, ri) = atoms[permindex[i]]
        resix.add(ri)
        resnames.add(rn)
        is_solute = is_solute or is_solute_atom
    resix = list(resix)
    resnames = list(resnames)
    resix.sort()
    if len(resnames) == 1:
        ret = resnames[0]
    else:
        ret = "Residues"
    ret += " "
    ret += str_of_list(resix)
    if is_solute:
        ret += "*"
    return ret
        
while True:
    def show_help():
        print("""commands:
list         List molecules ("*" represents solute)
split N R    Split molecule N just BEFORE residue nubmer R
pick N R     Pick residue R in molecule N and separate from other residues
merge N M    Merge Nth and Mth molecule into a single molecule
group N M    Group Nth and Mth molecule,
             N and M must have exactly the same number of molecules
save         Save
quit         Save and quit
QUIT         force quit without saving
""")
    
    def show_list(handle):
        for i in range(mols):
            print("%2d." % (i + 1), end=' ', file=handle)
            print("%5d" % ms[i], "mols", "%5d" % ns[i], "atoms", end=' ', file=handle)
            print(name_of(i), file=handle)

    def save_mol():
        global mols
        # super-duper ad-hoc but must be enough for the case...
        tarcmd = "tar cf `date +%m%d%H%M%S`.tar soln/MDinfo soln/MolPrm* refs/MDinfo refs/MolPrm*"
        if os.path.exists("soln/.extraparam"):
            tarcmd += " soln/.extraparam"
        os.system(tarcmd)
        os.system("rm -f soln/MolPrm*")
        os.system("rm -f refs/MolPrm*")
        # for metadata update with NFS async
        os.stat("soln")
        os.stat("refs")
        os.stat(".")

        fh = open("system-info", "wt")
        show_list(fh)
        safe_close(fh)

        # find solute
        solute = -1
        for i in range(mols):
            if name_of(i)[-1] == '*':
                solute = i
                break

        print("New solute position: ", solute + 1)

        global ms, ns, begins, permindex, permindex_refs, molprm

        for state in ["soln", "refs"]:
            # Update solute position
            if state == "soln":
                # for refs there are nothing like "solute" ...
                try:
                    ifh = open(state + "/.extraparam", "rt")
                    carryover = pickle.load(ifh)
                    ifh.close()
                except OSError:
                    # failed to read
                    carryover = {}

                carryover["sltspec"] = solute + 1
                ofh = open(state + "/.extraparam", "wt")
                pickle.dump(carryover, ofh)
                safe_close(ofh)

            # Update MDinfo
            fh = open(state + "/MDinfo", "wt")
            mstmp = [x for x in ms]
            nstmp = [x for x in ns]
            if state == "refs":
                mstmp[solute] -= 1
            if mstmp[solute] == 0:
                del mstmp[solute]
                del nstmp[solute]
                
            print("FRAMES %d" % len(mstmp), file=fh)
            for m in mstmp:
                print(m, end=' ', file=fh)
            print(file=fh)
            for n in nstmp:
                print(n, end=' ', file=fh)
            print(file=fh)
            safe_close(fh)
            molprmid = 1

            perm = open(state + "/PermIndex", "wt")
            if state == "refs":
                refi = 0
                for i in range(totalatoms):
                    orig = permindex[i]
                    (is_solute, rn, ri) = atoms[orig]
                    sol = ""
                    if is_solute:
                        sol = " (solute)"
                    x = permindex_refs[orig]
                    if x != None:
                        print("%6d %6d ! %s %d%s" % (orig + 1, refi + 1, rn, ri, sol), file=perm)
                        refi += 1
            else:
                for i in range(totalatoms):
                    x = permindex[i]
                    (is_solute, rn, ri) = atoms[x]
                    sol = ""
                    if is_solute:
                        sol = " (solute)"
                    print("%6d %6d ! %s %d%s" % (x + 1, i + 1, rn, ri, sol), file=perm)
            safe_close(perm)
                        
            for i in range(mols):
                # It's not output when solute has only one molecule
                # For both cases with soln / refs it applies
                # BTW: solute should have only one molecules because of assertions at the beginning
                if (i == solute and mstmp[i] == 1):
                    continue
                        
                fh = open(state + "/MolPrm%d" % molprmid, "wt")
                molprmid += 1
                for j in range(ns[i]):
                    print(molprms[permindex[begins[i] + j]], file=fh)
                safe_close(fh)
            
            # does not touch SltInfo

    def get_number_before(n, r):
        global begins
        ntot = begins[n + 1] - begins[n]
        for i in range(ntot):
            (_, _, ri) = atoms[permindex[begins[n] + i]]
            if ri == r:
                return i
        return -1

    def get_number_after(n, r):
        global begins
        before = get_number_before(n, r)
        if before == -1:
            # not found
            return -1
        ntot = begins[n + 1] - begins[n]
        for i in range(before, ntot):
            (_, _, ri) = atoms[permindex[begins[n] + i]]
            if ri != r:
                return i
        return ntot

    def split_impl(n, pos):
        global ns, ms, mols
        # no change in permindex
        ms.insert(n, 1)
        ns.insert(n, pos)
        ns[n + 1] -= pos
        begins.insert(n, begins[n])
        begins[n + 1] = begins[n] + pos
        mols += 1

    def split_at(n, r):
        global ns, ms, mols
        if n < 0 or n >= mols:
            print("Invalid molecular index")
            return
        if ms[n] != 1:
            print("Cannot split multiple molecules")
            return
        
        group_before = get_number_before(n, r)
        if group_before < 0 or group_before >= ns[n]:
            print("No such molecule in molecule %d" % n)
            return
        elif group_before == 0:
            print("No other molecule before residue %d" % r)
        split_impl(n, group_before)

    def merge_update_begins_permindex(n, m):
        global begins, permindex
        mthperm = permindex[begins[m]:begins[m+1]]
        del permindex[begins[m]:begins[m+1]]
        permindex[begins[n+1]:begins[n+1]] = mthperm
        mtot = begins[m+1] - begins[m]
        del begins[m]
        for i in range(n+1, m):
            # since no. m will be removed...
            begins[i] += mtot

    def merge_mol(n, m):
        global ns, ms, mols
        if n < 0 or m < 0 or n >= mols or m >= mols:
            print("Invalid molecular index")
            return
        if n == m:
            print("Cannot merge the same molecule")
            return
        if n > m:
            tmp = m
            m = n
            n = tmp
        merge_update_begins_permindex(n, m)
        ns[n] = ms[n] * ns[n] + ms[m] * ns[m]
        ms[n] = 1
        del ns[m]
        del ms[m]
        mols -= 1
        return

    def pick(n, r):
        global ns, ms, mols
        if n < 0 or n >= mols:
            print("Invalid molecular index")
            return
        if ms[n] != 1:
            print("Cannot pick multiple molecules")
            return
        
        group_before = get_number_before(n, r)
        if group_before < 0 or group_before >= ns[n]:
            print("No such molecule in molecule", n)
            return
        split_impl(n, group_before)
        group_after = get_number_after(n + 1, r)
        split_impl(n + 1, group_after)
        merge_mol(n, n + 2)

    def group_mol(n, m):
        global ns, ms, mols
        if n < 0 or m < 0 or n >= mols or m >= mols:
            print("Invalid molecular index")
            return
        if n == m:
            print("Cannot group the same molecule")
            return
        if ns[n] != ns[m]:
            print("Failed to regruop: number of atoms does not match")
            return
        if n > m:
            tmp = m
            m = n
            n = tmp
        merge_update_begins_permindex(n, m)
        ms[n] += ms[m]
        del ns[m]
        del ms[m]
        mols -= 1
        return

    log("NS: " + repr(ns))
    log("MS: " + repr(ms))
    log("BS: " + repr(begins))
    l = input("> ").strip().split()
    if l == []:
        show_help()
    elif l[0] == "list" or l[0] == "ls":
        show_list(sys.stdout)
    elif l[0] == "split":
        if len(l) != 3:
            show_help()
            continue
        try:
            n = int(l[1]) - 1
            r = int(l[2])
        except ValueError:
            show_help()
            continue
        split_at(n, r)
    elif l[0] == "pick":
        if len(l) != 3:
            show_help()
            continue
        try:
            n = int(l[1]) - 1
            r = int(l[2])
        except ValueError:
            show_help()
            continue
        pick(n, r)
    elif l[0] == "merge":
        if len(l) != 3:
            show_help()
            continue
        try:
            n = int(l[1]) - 1
            m = int(l[2]) - 1
        except ValueError:
            show_help()
            continue
        merge_mol(n, m)
    elif l[0] == "group":
        if len(l) != 3:
            show_help()
            continue
        try:
            n = int(l[1]) - 1
            m = int(l[2]) - 1
        except ValueError:
            show_help()
            continue
        group_mol(n, m)
    elif l[0] == "save":
        save_mol()
    elif l[0] == "quit":
        save_mol()
        exit(0)
    elif l[0] == "QUIT":
        exit(0)
    else:
        print("Unknown command:", l[0])
        show_help()

        
        
        

