#!/usr/bin/env python3

# popen and others are used only for 2.3 compatibility
import warnings
warnings.simplefilter("ignore", DeprecationWarning)

import os
import os.path
import sys
import pickle
import popen2
import re
from argparse import ArgumentParser

parser = ArgumentParser()

# topology, mandatory
parser.add_argument("-f", "--mdff", dest = "mdff",
                  help = "MODYLAS force field file (*.mdff)",
                  default = None)

# can be specified; otherwise specify interactively
parser.add_argument("-s", "--solute", dest = "solute",
                  help = "molecule-index of solute molecule (comma separated for multiple choice)",
                  default = None)

parser.add_argument("-v", "--verbose", dest = "verbose", action = "store_true",
                  help = "Increase verbosity (for debug)",
                  default = False)

options = parser.parse_args()

def log(x):
    if options.verbose:
        print(x, file=sys.stderr)

def warn_or_error(x, col):
    prefix = ""
    suffix = ""
    if os.isatty(sys.stderr.fileno()):
        prefix = "\x1b[" + str(col) + ";1m"
        suffix = "\x1b[0m"
    print(prefix + x + suffix, file=sys.stderr)

def warn(x):
    warn_or_error("Warning: " + x, 33)

def error(x):
    warn_or_error("Error: " + x, 31)
    sys.exit(1)

def safe_close(fh):
    # asynchronous NFS may miss file creation
    # esp. combined with delayed allocation (ext4, XFS)
    fh.flush()
    os.fsync(fh.fileno())
    fh.close()

if options.mdff == None:
    error("mdff must be specified (try --help)")

if not os.path.exists(options.mdff):
    print("Error: mdff file does not exist!", file=sys.stderr)
    sys.exit(1)

class union_find:
    """Tarjan's famous disjoint-set data structure.

    """
    def __init__(self, n):
        self.uftable_ = [-1] * n
    
    def union(self, i, j):
        pi = self.find(i)
        pj = self.find(j)
        if pi != pj:
            if self.uftable_[pj] < self.uftable_[pi]:
                temp = pi
                pi = pj
                pj = temp
            self.uftable_[pi] += self.uftable_[pj];
            self.uftable_[pj] = pi
    
    def find(self, i):
        if self.uftable_[i] < 0:
            return i
        else:
            newroot = self.find(self.uftable_[i])
            self.uftable_[i] = newroot
            return newroot

    def is_connected(self, i, j):
        pi = self.find(i)
        pj = self.find(j)
        return pi == pj

carryover = {}

class parse_modylas:
    def __init__(self,fname):
        fp = open(fname,"rt")
        self.dict = self.getelem([l.strip() for l in fp])
        fp.close()
    def getelem(self,str_list):
        assigned = False
        blockname = ""
        inblock = False
        for l in str_list:
            re_block_begin = re.compile(r"^<([^/].*)>$").match(l)
            if re_block_begin and (not inblock):
                inblock = True
                contents = []
                blockname = re_block_begin.group(1)
            else:
                if l == "</"+blockname+">":
                    inblock = False
                    if not assigned:
                        out = {}
                        assigned = True
                    if blockname not in out:
                        out[blockname] = []
                    out[blockname] += [self.getelem(contents)]
                else:
                    if inblock:
                        contents.append(l)
                    else:
                        re_equal = re.compile(r"^(.*)=(.*)$").match(l)
                        if re_equal:
                            if not assigned:
                                out = {}
                                assigned = True
                            out[re_equal.group(1).strip()] = re_equal.group(2).strip()
                        else:
                            if not assigned:
                                out = []
                                assigned = True
                            out.append(re.split(r" +",l.strip()))
        if not assigned:
            out = []
        return out

class topology:
    def __init__(self):
        self.atoms = []
        self.atom2index = {}
        self.atom2type = {}
        self.atom2charge = {}
        self.atom2moltype = {}
        self.atomtype2epsilon = {}
        self.atomtype2sigma = {}
        self.system = {}
        self.moleculetypes = {}
        self.molecules = []


    def process_pair_coeffs(self, ls):
        epsilon = float(ls[1])
        sigma   = float(ls[2])

    def read_data(self, mdff):
        pass

    # make system, moleculetypes, molecules, same as gromacs
    def make_system(self):

        self.system = []
        for array in mdff['system'][0]:
            self.system.append((array[0],int(array[1])))

        self.moleculetypes = {}
        for molno in range(len(self.system)):
            self.moleculetypes[self.system[molno][0]] = molno
        
        self.molecules = [None] * len(self.system)
        sumatomid = 0
        for molno in range(len(self.system)):
            mdffspec = mdff['topology and parameters'][0]['species'][molno]
            nsite = int(mdffspec['natom'])
            self.molecules[molno] = []
            for atomid in range(nsite):
                atype  = str(atomid + sumatomid)
                self.atomtype2epsilon[atype] = float(mdffspec['epsilon'][0][atomid][0])
                self.atomtype2sigma[atype] = float(mdffspec['r'][0][atomid][0]) * 0.5
                atom   = None # dummy
                charge = float(mdffspec['charge'][0][atomid][0])
                mass   = float(mdffspec['mass'][0][atomid][0])
                self.molecules[molno].append( [atype, atom, charge, mass] )
            sumatomid += nsite

mdff = parse_modylas(options.mdff).dict

top = topology()
top.read_data(mdff)
top.make_system()

mass_table = {
  1: 'H',
  2: 'D',
  12: 'C',
  14: 'N',
  15: 'CH3',
  16: 'O',
  19: 'F',
  23: 'Na',
  28: 'Si',
  31: 'P',
  32: 'S',
  35: 'Cl',
  36: 'Cl',
  40: 'Ca',
  56: 'Fe',
  63: 'Cu',
  64: 'Cu',
  65: 'Zn',
  80: 'Br',
  0: 'M' } # dummy atom

def atomtype_of_mass(mass):
    imass = int(round(mass))
    if imass not in mass_table:
        warn("Could not find appropriate atom type from mass (%f); replacing with carbon (12.0)" % mass)
        return 'C'
    return mass_table[imass]

def get_topology_info():
    # make list of segment names
    mollist = [s for (s, _n) in top.system]

    # python 2.3 does not have set()
    if options.solute:
        solutes = options.solute.split(',')
    else:
        # interactive input
        print("Molecule types in topology file:", end=' ')
        for s in mollist:
            print(s, end=' ')
        print()
        l = input("Which molecules are solutes? (For multiple choice please specify as comma-separated list) ").split(',')
        solutes = [x.strip() for x in l]

    if solutes == []:
        error("Solute list is empty")

    for s in solutes:
        if s not in mollist:
            error("No such segname in topology: %s" % s)

    # At this moment solute can be one of the follows:
    # * Solute spans several contiguous molecular types.
    #   In this case, these contiguous types should be treated as a single molecule.
    # * Solute spans a single molecular type.
    #   In this case, multiple solute molecules may exist

    # check contiguous or not
    end_solute = False
    for i in range(len(mollist) - 1):
        mol1 = mollist[i]
        mol2 = mollist[i + 1]
        if (mol1 in solutes) and (mol2 not in solutes):
                end_solute = True
        if (mol2 in solutes) and end_solute:    
            error("Solute is not contiguous")

    return solutes

solutes = get_topology_info()

# consolidate solutes
solute_single = (len(solutes) == 1)

mols = []
if solute_single:
    # output as in topology (supports multiple solute)
    for (s, n) in top.system:
        molno = top.moleculetypes[s]
        mols.append(([s], n, s in solutes, top.molecules[molno]))
else:
    # merge solute and output as a single molecule
    soluteatoms = []
    for (s, n) in top.system:
        if (s in solutes):
            molno = top.moleculetypes[s]
            soluteatoms += top.molecules[molno] * n

    solute_first = True
    for (s, n) in top.system:
        if s in solutes:
            if solute_first:
                mols.append((solutes, 1, True, soluteatoms))
                solute_first = False
        else:
            molno = top.moleculetypes[s]
            mols.append((s, n, False, top.molecules[molno]))

def gen(mode):
    import copy

    if not os.path.exists(mode):
        os.mkdir(mode)

    curmols = copy.deepcopy(mols)
    nmols = []
    sites = []
    # edit molecules for refs: for multiple solutes with n molecules,
    # refs regards them as 1 solute + (n-1) solvents
    if mode == "refs":
        for i in range(len(mols)):
            (s, n, is_solute, atoms) = mols[i]
            if is_solute and n > 1:
                curmols[i:i+1] = [(s, 1, True, atoms),
                                  (s, n-1, False, atoms)]
                break
 
    nmols = [n for (_, n, is_solute, _) in curmols
             if not (mode == "refs" and is_solute)]
    sites = [len(atoms) for (_, _, is_solute, atoms) in curmols
             if not (mode == "refs" and is_solute)]

    if mode == "soln":
        for i in range(len(mols)):
            if curmols[i][2]:
                carryover["sltpick"] = i + 1 # 1-origin

    # output MDinfo
    mdifh = open(mode + "/MDinfo", "wt")
    print("FRAMES %d" % len(nmols), file=mdifh)
    
    for n in nmols:
        print("%d" % n, end=' ', file=mdifh)
    print(file=mdifh)
    for n in sites:
        print("%d" % n, end=' ', file=mdifh)
    print(file=mdifh)
    mdifh.close()
    
    solvent_cnt = 1
    ofh = None
    for (s, n, is_solute, atoms) in curmols:
        if is_solute:
            fn = "SltInfo"
            if n > 1:
                solvent_cnt += 1
        else:
            fn = "MolPrm%d" % solvent_cnt
            solvent_cnt += 1

        k = 1

        if ofh:
            safe_close(ofh)
        ofh = open(mode + "/" + fn, "wt")

        for (atype, _atom, charge, mass) in atoms:
            eps = top.atomtype2epsilon[atype]
            sig = top.atomtype2sigma[atype]
            atom = atomtype_of_mass(float(mass))
            print(("%d %s %.8g %.8g %.8g" % 
                           (k, atom, charge, eps, sig)), file=ofh)
            k += 1

    safe_close(ofh)
    # write carryover
    ofh = open(mode + "/.extraparam", "wt")
    pickle.dump(carryover, ofh)
    safe_close(ofh)

gen("soln")
gen("refs")
